services:
  - type: web
    name: Scale&Figures
    env: python
    buildCommand: "./build.sh" 
    startCommand: "gunicorn ecommerce_project.wsgi:application"
    healthCheckPath: /admin/login/ 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ecommerce_db 
          property: connectionString
      - key: SECRET_KEY
        generateValue: true 
      - key: WEB_CONCURRENCY
        value: 1
        value: "False" 
      - key: DISABLE_COLLECTSTATIC
        value: "0" 

  - type: pserv
    name: ecommerce_db
    plan: free 
    ipAllowList: [] 
    databaseName: ecommerce_db 
    user: ecommerce_user
